### ISSUE TITLE
Missing `get` on Matrix

### ISSUE THREAD

**Issue by hellow554** [LukasKalbertodt/lina#3]
Matrix does implement the `Index` trait, but doesn't have a `get` method for bound checking access.

**Comment by LukasKalbertodt** [comment]
Did you actually needed the `get` method at some point? If so, could you share some code where it might be useful?

**Comment by LukasKalbertodt** [comment]
Since I didn't get a reply here and since I now removed the `Index` impl, I will close this issue.
